---

  - name: install nodejs
    apt: name=nodejs state=present update_cache=yes

# create a directory if it doesnt exist
  - file: path=/home/vagrant/applications 
      state=directory 
      mode=0755

# app files
  - name: "deploy appserver file"
    copy: src=server.js
      dest=/home/vagrant/
      owner=vagrant mode=0644

  - shell: "nohup node /home/vagrant/server.js &"