---

# create a directory if it doesnt exist
  - file: path=/home/vagrant/applications 
      state=directory 
      mode=0755

# app files
  - name: "deploy appserver file"
    copy: src=server.js
      dest=/home/vagrant/
      owner=vagrant mode=0644

  - name: "Check list of Node.js apps running."
    command: forever list
    register: forever_list
    changed_when: false      

  - name: "Start  Node.js app."
    command: forever start /home/vagrant/server.js
    when: "forever_list.stdout.find('/home/vagrant/server.js') == -1"